

void main(void)
{ 
    // get invocation unique seed value for RNG
    uint seed = generateSeed();

    // acquire previous state (whether global or local)  
    state nS;  
    copyPreviousState(nS);

    // progress state
    progressState(nS, seed);

    // peturb state
    perturbState(nS, seed);

    // store state
    storeState(nS, seed);
    
    barrier();

    if (uLoadLocal == 1)
    {
        // update group states
        updateGroupStates(seed);
    }
}
